import type { Config } from "tailwindcss";

/** Tokens from Stitch export — Nexus ARPG Storefront / Home VAULT.ARPG */
const stitchColors = {
  tertiary: "#ffb3b6",
  "on-secondary-container": "#b4b5b5",
  "primary-container": "#0f0f0f",
  "on-tertiary-fixed-variant": "#920028",
  surface: "#141313",
  "on-secondary": "#2f3131",
  "surface-dim": "#141313",
  "tertiary-fixed": "#ffdada",
  "on-primary-fixed-variant": "#474646",
  outline: "#8e9192",
  "surface-container-highest": "#353434",
  "inverse-on-surface": "#313030",
  "surface-tint": "#c8c6c5",
  "error-container": "#93000a",
  "on-surface-variant": "#c4c7c7",
  "secondary-container": "#454747",
  "primary-fixed-dim": "#c8c6c5",
  "surface-container-lowest": "#0e0e0e",
  primary: "#c8c6c5",
  "primary-fixed": "#e5e2e1",
  "on-primary-container": "#7d7b7b",
  "surface-container-low": "#1c1b1b",
  "on-tertiary-container": "#ed284f",
  "on-secondary-fixed-variant": "#454747",
  "tertiary-fixed-dim": "#ffb3b6",
  error: "#ffb4ab",
  secondary: "#c6c6c7",
  "tertiary-container": "#290005",
  "on-primary-fixed": "#1c1b1b",
  "surface-bright": "#3a3939",
  "on-secondary-fixed": "#1a1c1c",
  "surface-container-high": "#2b2a2a",
  "on-tertiary": "#68001a",
  "secondary-fixed": "#e2e2e2",
  "inverse-primary": "#5f5e5e",
  "on-surface": "#e5e2e1",
  "on-background": "#e5e2e1",
  "on-error-container": "#ffdad6",
  "surface-container": "#201f1f",
  "surface-variant": "#353434",
  "on-primary": "#313030",
  "secondary-fixed-dim": "#c6c6c7",
  background: "#141313",
  "on-error": "#690005",
  "on-tertiary-fixed": "#40000c",
  "inverse-surface": "#e5e2e1",
  "outline-variant": "#444748",
} as const;

export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: stitchColors,
      spacing: {
        base: "4px",
        "section-gap": "80px",
        gutter: "24px",
        "margin-page": "48px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      borderRadius: {
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        h3: ["var(--font-inter)", "sans-serif"],
        h1: ["var(--font-inter)", "sans-serif"],
        body: ["var(--font-inter)", "sans-serif"],
        button: ["var(--font-inter)", "sans-serif"],
        h2: ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "meta-mono": ["var(--font-space-grotesk)", "monospace"],
      },
      fontSize: {
        h3: ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        h1: ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        body: ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        button: ["14px", { lineHeight: "1", fontWeight: "500" }],
        h2: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "meta-mono": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      backgroundImage: {
        scanlines: "linear-gradient(to bottom, rgba(255,255,255,0) 50%, rgba(0,0,0,0.1) 50%)",
      },
    },
  },
  plugins: [],
} satisfies Config;
